### ISSUE TITLE
File public/img/logo.png missing

### ISSUE THREAD

**Issue by joeljuca** [IgorAntun/unsplashify#2]
I've got a JavaScript error when trying to launch Unsplashify:

![captura de tela 2015-08-28 20 24 56](https://cloud.githubusercontent.com/assets/673884/9559002/e390a6f2-4dc2-11e5-8a07-4151ed55a75b.png)

```
Uncaught Exception:
TypeError: Error processing argument 0.
    at TypeError (native)
    at EventEmitter.<anonymous> (/Users/joel/Sites/unsplashify/main.js:43:19)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
```

It seems that you forgot to commit the logo, requested on line 32 of `main.js`. :)

**Comment by igorantun** [comment]
Should be fixed as of 9477dc67fd4849aeb9eb06a142a819c5963fff15
Please tell me if this fixes it.

**Comment by joeljuca** [comment]
Fixed.

**Comment by igorantun** [comment]
Awesome, thanks!
